
name: OTP_v1
description: Proyecto Final OTP

environment:
  sdk: ">=3.2.0 <4.0.0"  # ajusta a tu versiÃ³n de Dart/Flutter

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  flutter_secure_storage: ^9.2.4
  pointycastle: ^3.9.1
  basic_utils: ^5.7.0
  crypto: ^3.0.3
  google_fonts: ^6.2.0
  flutter_svg: ^2.0.9    # si usas logo en SVG (opcional)

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/LogoConsorcio.svg
    - assets/Splash.png
